

SRC+= unit-tests/fan_ut/test_ASFile.c   
SRC+= unit-tests/fan_ut/test_runnerASFile.c 
SRC+= unit-tests/fan_ut/test_main.c 


SRC+= Core/Src/fan.c


INC_DIR+= -ICore/Inc/ 



COVERAGE_SOURCEDIR :=
COVERAGE_SOURCEDIR +=Core/Src/


MOCKED_HEADER +=  Core/Inc/fan.h


# MOCKED_SOURCE +=  build/UnitTests/cmock/mock_fan.c


SRC+= $(MOCKED_SOURCE)
